[project]
name = "proxy-server"
version = "0.1.1"
description = "A simple proxy server implemented in Python."
readme = "README.md"
requires-python = ">=3.13,<=3.14"
license = { text = "MIT" }
dependencies = [
    "fastapi==0.119.0",
    "mysql-connector==2.2.9",
    "pydantic==2.12.0",
    "requests==2.32.5",
    "uvicorn==0.38.0",
]

[dependency-groups]
dev = [
    "ruff==0.14.1",
    "bandit==1.8.6",
    "pyright==1.1.406",
]

[tool.bandit]
exclude_dirs = [".venv"]
