version: '3.8'

services:
  minimal-cors-server:
    build:
      context: https://github.com/MatthiasHarzer/minimal-cors-server.git
      dockerfile: Dockerfile

    environment:
      - CACHE_MODE=memory

    ports:
      - "9996:8000"
    restart: always
