version: '3.8'

services:
  proxy-server:
    image: ghcr.io/matthiasharzer/proxy-server:latest

    environment:
      - CACHE_MODE=mysql
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_DATABASE=proxy
      - MYSQL_PASSWORD=secret

    ports:
      - "9996:8080"
    restart: always
