version: '3.8'

services:
  proxy-server:
    image: ghcr.io/matthiasharzer/proxy-server:latest

    environment:
      - CACHE_MODE=sqlite
      - SQLITE_FILE=data/db/sqlite.db

    volumes:
      - ./data:/app/data

    ports:
      - "9996:8080"
    restart: always
