version: '3.8'

services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - CACHE_MODE=sqlite
      - SQLITE_FILE=data/db/sqlite.db

    volumes:
      - ./data:/app/data

    ports:
      - "9996:8000"
    restart: always
